import type { Product } from "./types"

export const products: Product[] = [
  {
    id: "1",
    name: "Classic Denim Jacket",
    brand: "Levi's",
    price: 89.99,
    originalPrice: 129.99,
    discount: 31,
    image: "/classic-blue-denim-jacket.png",
    category: "Jackets",
    rating: 4.5,
    reviews: 128,
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Blue", "Black", "Light Blue"],
    description: "Timeless denim jacket perfect for any casual outfit.",
    inStock: true,
  },
  {
    id: "2",
    name: "Premium Cotton T-Shirt",
    brand: "Calvin Klein",
    price: 24.99,
    originalPrice: 39.99,
    discount: 38,
    image: "/white-premium-cotton-t-shirt.png",
    category: "T-Shirts",
    rating: 4.3,
    reviews: 89,
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["White", "Black", "Navy", "Gray"],
    description: "Soft, comfortable cotton t-shirt with a perfect fit.",
    inStock: true,
  },
  {
    id: "3",
    name: "Slim Fit Chinos",
    brand: "Tommy Hilfiger",
    price: 59.99,
    originalPrice: 89.99,
    discount: 33,
    image: "/khaki-slim-fit-chino-pants.png",
    category: "Pants",
    rating: 4.4,
    reviews: 156,
    sizes: ["28", "30", "32", "34", "36", "38"],
    colors: ["Khaki", "Navy", "Black", "Olive"],
    description: "Versatile chinos that work for both casual and smart-casual looks.",
    inStock: true,
  },
  {
    id: "4",
    name: "Wool Blend Sweater",
    brand: "Ralph Lauren",
    price: 79.99,
    originalPrice: 120.0,
    discount: 33,
    image: "/navy-wool-blend-sweater.png",
    category: "Sweaters",
    rating: 4.6,
    reviews: 203,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Navy", "Gray", "Burgundy", "Forest Green"],
    description: "Cozy wool blend sweater perfect for cooler weather.",
    inStock: true,
  },
  {
    id: "5",
    name: "Athletic Sneakers",
    brand: "Nike",
    price: 94.99,
    originalPrice: 130.0,
    discount: 27,
    image: "/white-athletic-sneakers.png",
    category: "Shoes",
    rating: 4.7,
    reviews: 342,
    sizes: ["7", "8", "9", "10", "11", "12"],
    colors: ["White", "Black", "Gray"],
    description: "Comfortable athletic sneakers for everyday wear and workouts.",
    inStock: true,
  },
  {
    id: "6",
    name: "Leather Crossbody Bag",
    brand: "Coach",
    price: 149.99,
    originalPrice: 225.0,
    discount: 33,
    image: "/brown-leather-crossbody-bag.png",
    category: "Accessories",
    rating: 4.8,
    reviews: 97,
    sizes: ["One Size"],
    colors: ["Brown", "Black", "Tan"],
    description: "Elegant leather crossbody bag perfect for any occasion.",
    inStock: true,
  },
  {
    id: "7",
    name: "Button-Down Shirt",
    brand: "Brooks Brothers",
    price: 49.99,
    originalPrice: 79.99,
    discount: 38,
    image: "/white-button-down-dress-shirt.png",
    category: "Shirts",
    rating: 4.4,
    reviews: 167,
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["White", "Light Blue", "Pink", "Gray"],
    description: "Classic button-down shirt suitable for business and casual wear.",
    inStock: true,
  },
  {
    id: "8",
    name: "Quilted Vest",
    brand: "Patagonia",
    price: 69.99,
    originalPrice: 99.99,
    discount: 30,
    image: "/navy-quilted-vest.png",
    category: "Outerwear",
    rating: 4.5,
    reviews: 134,
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Navy", "Black", "Forest Green"],
    description: "Lightweight quilted vest perfect for layering.",
    inStock: true,
  },
]
